# This file contains the [pre-commit](https://pre-commit.com/) configuration of this repository.
# More on which specific pre-commit hooks we use can be found in README.md.
---
minimum_pre_commit_version: "2.9.2"
repos:
  - repo: meta
    hooks:
      - id: identity
      - id: check-hooks-apply
  - repo: local
    hooks:
      - id: isort
        name: iSort - Sorts imports.
        description: Sorts your import for you.
        entry: isort
        language: python
        types: [python]
        require_serial: true
      - id: black
        name: Black - Auto-formatter.
        description: Black is the uncompromising Python code formatter. Writing to files.
        entry: black
        language: python
        types: [python]
        require_serial: true
      - id: flake8
        name: Flake8 - Enforce code style and doc.
        description: A command-line utility for enforcing style consistency across Python projects.
        entry: flake8
        args: ["--config=.flake8"]
        language: python
        types: [python]
        require_serial: true
#      - id: pytype
#        name: pytype - A static type analyzer for Python code
#        description: Pytype checks and infers types for your Python code - without requiring type annotations.
#        entry: pytype
#        args: ["--config=pytype.cfg", "--jobs auto"]
#        language: python
#        types: [python]
#        require_serial: true
#        verbose: true
