version: 2

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
    - requirements: docs/requirements-docs.txt

formats:
  - pdf
  - epub
