name: Publish to PyPI
on:
  release:
    types: [published]

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source-code repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Flit
        run: pip install flit
      - name: Install Dependencies
        run: flit install --symlink
      - name: Publish
        run: flit publish
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
