name: Validate

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0

  test:
    strategy:
      matrix:
        python-version: [
          "3.8",
          "3.9",
          "3.10",
          "3.11",
        ]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      TOXENV: py
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install -U tox
      - name: Run tox
        run: python -m tox
      - name: Generate coverage.xml
        run: python -m tox -e coverage
      - name: Report coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./.tox/coverage.xml
          name: ${{ matrix.os }}:${{ matrix.python-version }}
          fail_ci_if_error: true

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.6
      - name: Install tox
        run: python -m pip install -U tox
      - name: Run tox
        run: python -m tox -e docs

  build-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install tox
        run: python -m pip install -U tox
      - name: Run tox
        run: python -m tox -e build
      - name: Check generation
        run: |
          exactly_one() {
            value=$(find dist -iname $1 | wc -l)
            if [ $value -ne 1 ]; then
              echo "Found $value instances of $1, not 1"
              return 1
            else
              echo "Found exactly 1 instance of $value"
            fi
          }
          # Check that exactly one tarball and one wheel are created
          exactly_one '*.tar.gz'
          exactly_one '*.whl'